/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'event.sensor.process': EventHandler<{ sensorId: string; value: number; unit: string; type: string; timestamp: string; date: string }, never>
    'api.user.preferences': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'api.sensor.ingest': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'sensor.reading.created'; data: { sensorId: string; value: number; unit: string; type: string; timestamp: string; date: string } }>
  }
    
}